### ISSUE TITLE
module 'tensorflow' has no attribute 'placeholder' 

### ISSUE THREAD

**Issue by mattiat** [RViMLab/NSR2018-AOSLO-photoreceptor-detection#1]
Hello and thank you for sharing your tool.
I recently installed on Windows 10, python 3.7, tensorflow 2.4.1.
"Apply existing model" -> "Run"  (on data in NSR2018-AOSLO-photoreceptor-detection/example_data)
I encounter the following error (the cmd window disappears immediately, but I was able to take a screenshot)

![image](https://user-images.githubusercontent.com/365700/115395054-bcac7900-a1e3-11eb-96f5-4e5c1ce85894.png)

Thank you, Mattia

**Comment by mattiat** [comment]
I tried some fixes from https://stackoverflow.com/questions/37383812/tensorflow-module-object-has-no-attribute-placeholder
I installed an older version of tensorflow as suggested here by mahbubcseju. I went for 1.7.

Got
![image](https://user-images.githubusercontent.com/365700/115592152-2c4d6180-a2d3-11eb-8b95-6daf74f77c00.png)

**Comment by cbergeles** [comment]
Hi @mattiat, did the conversation with Ben address this issue?

**Comment by mattiat** [comment]
Yes, sorry, solved by https://github.com/RViMLab/NSR2018-AOSLO-photoreceptor-detection/pull/2 
Thank you for the help!
